parameters:
  env(TOKEN): ''
  env(BUCKET_NAME): ''
  env(PUBLIC_ASSETS_BASE_URL): ''
  github_token: '%env(TOKEN)%'
  bucket_name: '%env(BUCKET_NAME)%'
  module_list_repository: 'prestashop/native-modules'
  public_assets_base_url: '%env(PUBLIC_ASSETS_BASE_URL)%'
  prestashop_min_version: '8.0.0-beta'