imports:
  - { resource: parameters.yaml }

services:
  _defaults:
    public: false
    autowire: true
    bind:
      $jsonDir: '%kernel.project_dir%/public/json'
      $moduleDir: '%kernel.project_dir%/var/tmp/modules'
      $prestaShopDir: '%kernel.project_dir%/var/tmp/prestashop'
      $moduleListRepository: '%module_list_repository%'
      $prestaShopMinVersion: '%prestashop_min_version%'
      $publicAssetsBaseUrl: '%public_assets_base_url%'

  Symfony\Component\Console\Application:
    public: true

  Github\Client:
    calls:
      - authenticate: ['%github_token%', 'access_token_header']

  Google\Cloud\Storage\StorageClient:

  Google\Cloud\Storage\Bucket:
    factory: ['@Google\Cloud\Storage\StorageClient', 'bucket']
    arguments: ['%bucket_name%']

  GuzzleHttp\Client:

  Psssst\ModuleParser:

  App\Util\ModuleUtils:

  App\Util\PrestaShopUtils:

  App\Util\PublicDownloadUrlProvider:

  App\Command\GenerateJsonCommand:
    tags: ['console.command']

  App\Command\UpdateModuleConfigFilesCommand:
    tags: ['console.command']

  App\Command\DownloadNativeModuleMainClassesCommand:
    tags: ['console.command']

  App\Command\DownloadNewPrestaShopReleasesCommand:
    tags: ['console.command']

  App\Command\CleanCommand:
    tags: ['console.command']

  App\Command\CheckReposCommand:
    tags: ['console.command']

  App\Command\UploadAssetsCommand:
    tags: ['console.command']

  App\Command\RunCommand:
    tags: ['console.command']
